




































































































































































 99%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎ | 263/265 [05:29<00:02,  1.24s/it]

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 265/265 [05:32<00:00,  1.25s/it]
Traceback (most recent call last):
  File "train.py", line 102, in <module>
    main(config)
  File "train.py", line 90, in main
    trainer.train()
  File "/opt/ml/baseline/trainer/trainer.py", line 223, in train
    avrg_loss, acc, f1 = self.validation(epoch + 1)
  File "/opt/ml/baseline/trainer/trainer.py", line 292, in validation
    data = new_df.groupby(["label_answer"])["preds"].value_counts().unstack()
  File "/opt/conda/lib/python3.8/site-packages/pandas/core/frame.py", line 6515, in groupby
    return DataFrameGroupBy(
  File "/opt/conda/lib/python3.8/site-packages/pandas/core/groupby/groupby.py", line 525, in __init__
    grouper, exclusions, obj = get_grouper(
  File "/opt/conda/lib/python3.8/site-packages/pandas/core/groupby/grouper.py", line 786, in get_grouper
    raise KeyError(gpr)
KeyError: 'label_answer'
Traceback (most recent call last):
  File "train.py", line 102, in <module>
    main(config)
  File "train.py", line 90, in main
    trainer.train()
  File "/opt/ml/baseline/trainer/trainer.py", line 223, in train
    avrg_loss, acc, f1 = self.validation(epoch + 1)
  File "/opt/ml/baseline/trainer/trainer.py", line 292, in validation
    data = new_df.groupby(["label_answer"])["preds"].value_counts().unstack()
  File "/opt/conda/lib/python3.8/site-packages/pandas/core/frame.py", line 6515, in groupby
    return DataFrameGroupBy(
  File "/opt/conda/lib/python3.8/site-packages/pandas/core/groupby/groupby.py", line 525, in __init__
    grouper, exclusions, obj = get_grouper(
  File "/opt/conda/lib/python3.8/site-packages/pandas/core/groupby/grouper.py", line 786, in get_grouper
    raise KeyError(gpr)
KeyError: 'label_answer'