2022-02-26 00:50:11,944 INFO    MainThread:7643 [wandb_setup.py:_flush():75] Loading settings from /opt/ml/.config/wandb/settings
2022-02-26 00:50:11,944 INFO    MainThread:7643 [wandb_setup.py:_flush():75] Loading settings from /opt/ml/baseline/wandb/settings
2022-02-26 00:50:11,944 INFO    MainThread:7643 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-02-26 00:50:11,944 INFO    MainThread:7643 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program_relpath': 'train.py', 'program': 'train.py'}
2022-02-26 00:50:11,944 INFO    MainThread:7643 [wandb_init.py:_log_setup():386] Logging user logs to /opt/ml/baseline/wandb/run-20220226_005011-3oi3gtdw/logs/debug.log
2022-02-26 00:50:11,944 INFO    MainThread:7643 [wandb_init.py:_log_setup():387] Logging internal logs to /opt/ml/baseline/wandb/run-20220226_005011-3oi3gtdw/logs/debug-internal.log
2022-02-26 00:50:11,944 INFO    MainThread:7643 [wandb_init.py:init():420] calling init triggers
2022-02-26 00:50:11,944 INFO    MainThread:7643 [wandb_init.py:init():425] wandb.init called with sweep_config: {}
config: {'epochs': 10, 'batch_size': 64, 'learning_rate': 0.0001}
2022-02-26 00:50:11,945 INFO    MainThread:7643 [wandb_init.py:init():471] starting backend
2022-02-26 00:50:11,945 INFO    MainThread:7643 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-02-26 00:50:11,958 INFO    MainThread:7643 [backend.py:ensure_launched():219] starting backend process...
2022-02-26 00:50:11,968 INFO    MainThread:7643 [backend.py:ensure_launched():224] started backend process with pid: 7679
2022-02-26 00:50:11,970 INFO    MainThread:7643 [wandb_init.py:init():480] backend started and connected
2022-02-26 00:50:11,973 INFO    MainThread:7643 [wandb_init.py:init():550] updated telemetry
2022-02-26 00:50:11,974 INFO    MainThread:7643 [wandb_init.py:init():581] communicating current version
2022-02-26 00:50:12,524 WARNING MainThread:7643 [wandb_init.py:init():972] interrupted
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 951, in init
    run = wi.init()
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 582, in init
    check = backend.interface.communicate_check_version(
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 92, in communicate_check_version
    ret = self._communicate_check_version(check_version)
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 413, in _communicate_check_version
    result = self._communicate(rec)
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 213, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/interface/router.py", line 37, in get
    is_set = self._object_ready.wait(timeout)
  File "/opt/conda/lib/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "/opt/conda/lib/python3.8/threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 959, in init
    getcaller()
  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 670, in getcaller
    print("Problem at:", src, line, func)
KeyboardInterrupt
